# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d633c52d3a56082dce19e7ba841fbca"
name = "functions-estudo"
handle = "functions-estudo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "marina-lindaa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_cart_transforms,write_delivery_customizations,write_discounts,write_inventory,write_payment_customizations,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
